export const profiles = [
	{
		categories: ["diseño"],
		name: "Mateo Riva",
		description: "Especialista en diseño de sistemas interactivos.",
		email: "mateo@gmail.com",
		city: "Madrid",
		projects: 12,
		experience: "5 años",
		tools: ["Figma", "Adobe", "Sketch", "GIMP"],
		avatar: "https://i.pravatar.cc/150?img=1",
	},
	{
		categories: ["gestión", "desarrollo"],
		name: "Sofía Chen",
		description:
			"Especialista en desarrollo de software y gestión de proyectos.",
		email: "sofia@gmail.com",
		city: "Tokio",
		projects: 30,
		experience: "6 años",
		tools: ["React", "Node", "SQL", "Trelo"],
		avatar: "https://i.pravatar.cc/150?img=2",
	},
	{
		categories: ["marketing"],
		name: "Lucas Fernández",
		description: "Especialista en marketing digital y diseño de estrategias.",
		email: "lucas@gmail.com",
		city: "Buenos Aires",
		projects: 22,
		experience: "3 años",
		tools: ["SEO", "Analytics", "ADS", "Canva"],
		avatar: "https://i.pravatar.cc/150?img=3",
	},
	{
		categories: ["backend", "desarrollo"],
		name: "Valentín Ruiz",
		description: "Especialista en desarrollo backend con Node.js.",
		email: "valentin@gmail.com",
		city: "Córdoba",
		projects: 50,
		experience: "10+ años",
		tools: ["Node", "Express", "SQL", "Docker"],
		avatar: "https://i.pravatar.cc/150?img=4",
	},
	{
		categories: ["frontend", "desarrollo"],
		name: "Tomasa García",
		description: "Especialista en interfaces modernas y diseños responsivos.",
		email: "tomasa@gmail.com",
		city: "Cataluña",
		projects: 5,
		experience: "1 año",
		tools: ["HTML", "CSS", "TypeScript", "Vue"],
		avatar: "https://i.pravatar.cc/150?img=5",
	},
	{
		categories: ["devops"],
		name: "Camilo Torres",
		description: "Especialista en DevOps y automatización de procesos.",
		email: "camilo@gmail.com",
		city: "Santiago",
		projects: 8,
		experience: "2 años",
		tools: ["AWS", "Docker", "CI/CD", "ELK"],
		avatar: "https://i.pravatar.cc/150?img=6",
	},
	{
		categories: ["diseño", "devops"],
		name: "Diego Morales",
		description: "Especialista en diseños modernos y DevOps.",
		email: "diego@gmail.com",
		city: "Lima",
		projects: 35,
		experience: "8 años",
		tools: ["Python", "SQL", "Canva", "Figma"],
		avatar: "https://i.pravatar.cc/150?img=7",
	},
	{
		categories: ["gestión"],
		name: "Lucía Herrera",
		description:
			"Especialista en entrega, conectando la visión del producto con el tecnicismo.",
		email: "lucia@gmail.com",
		city: "Montevideo",
		projects: 45,
		experience: "10+ años",
		tools: ["ERP", "CRM", "Wrike", "Trello"],
		avatar: "https://i.pravatar.cc/150?img=9",
	},
	{
		categories: ["backend", "frontend"],
		name: "Agustina Vega",
		description: "Especialista en desarrollo de aplicaciones fullstack.",
		email: "agustina@gmail.com",
		city: "Guadalajara",
		projects: 16,
		experience: "5 años",
		tools: ["Svelte", "Next", "Redux", "Mongo"],
		avatar: "https://i.pravatar.cc/150?img=10",
	},
	{
		categories: ["marketing"],
		name: "Martín Silva",
		description:
			"Especialista en marketing digital y estrategias de crecimiento.",
		email: "martin@gmail.com",
		city: "Bogotá",
		projects: 60,
		experience: "15+ años",
		tools: ["Asana", "Monday", "Jira", "Trello"],
		avatar: "https://i.pravatar.cc/150?img=11",
	},
];
